// ── Data: languages, topics, hints, fillers, connectors ────────────────────

const LANGS = [
  { code: "en-US", key: "en", name: "English",    short: "EN" },
  { code: "de-DE", key: "de", name: "Deutsch",    short: "DE" },
  { code: "es-ES", key: "es", name: "Español",    short: "ES" },
  { code: "fr-FR", key: "fr", name: "Français",   short: "FR" },
  { code: "it-IT", key: "it", name: "Italiano",   short: "IT" },
  { code: "pt-BR", key: "pt", name: "Português",  short: "PT" },
  { code: "pl-PL", key: "pl", name: "Polski",     short: "PL" },
  { code: "uk-UA", key: "uk", name: "Українська", short: "UA" },
];

const DIFFS = [
  { id: "easy",   label: "Easy",   cefr: "A1–A2", desc: "Everyday topics: family, food, hobbies" },
  { id: "medium", label: "Medium", cefr: "B1–B2", desc: "Experience and opinions: travel, work, plans" },
  { id: "hard",   label: "Hard",   cefr: "C1–C2", desc: "Discussion: society, technology, ethics" },
];

// Each topic: title (t) and 3 hint phrases (h) per language.
const TOPICS = {
  easy: [
    {
      t: { en: "My family", de: "Meine Familie", es: "Mi familia", fr: "Ma famille", it: "La mia famiglia", pt: "Minha família", pl: "Moja rodzina", uk: "Моя родина" },
      h: {
        en: ["There are … people in my family", "My mother and father are…", "We like to … together"],
        de: ["Meine Familie besteht aus…", "Meine Eltern sind…", "Zusammen … wir gern"],
        es: ["En mi familia somos…", "Mis padres son…", "Juntos nos gusta…"],
        fr: ["Dans ma famille, nous sommes…", "Mes parents sont…", "Ensemble, nous aimons…"],
        it: ["Nella mia famiglia siamo…", "I miei genitori sono…", "Insieme ci piace…"],
        pt: ["Na minha família somos…", "Meus pais são…", "Juntos, gostamos de…"],
        pl: ["W mojej rodzinie jest…", "Moi rodzice są…", "Razem lubimy…"],
        uk: ["У моїй родині є…", "Мої батьки…", "Разом ми любимо…"],
      },
    },
    {
      t: { en: "Favourite food", de: "Lieblingsessen", es: "Mi comida favorita", fr: "Ma cuisine préférée", it: "Il mio cibo preferito", pt: "Comida favorita", pl: "Ulubione jedzenie", uk: "Улюблена їжа" },
      h: {
        en: ["My favourite dish is…", "For breakfast I usually…", "I can / can't cook…"],
        de: ["Mein Lieblingsgericht ist…", "Zum Frühstück esse ich meistens…", "Ich kann (nicht) gut kochen…"],
        es: ["Mi plato favorito es…", "Para desayunar suelo…", "(No) sé cocinar…"],
        fr: ["Mon plat préféré, c'est…", "Au petit-déjeuner, je prends…", "Je (ne) sais (pas) cuisiner…"],
        it: ["Il mio piatto preferito è…", "A colazione di solito…", "(Non) so cucinare…"],
        pt: ["Meu prato favorito é…", "No café da manhã, eu costumo…", "Eu (não) sei cozinhar…"],
        pl: ["Moje ulubione danie to…", "Na śniadanie zwykle…", "(Nie) umiem gotować…"],
        uk: ["Моя улюблена страва — це…", "На сніданок я зазвичай…", "Я (не) вмію готувати…"],
      },
    },
    {
      t: { en: "My typical day", de: "Mein Alltag", es: "Mi día típico", fr: "Ma journée type", it: "La mia giornata", pt: "Meu dia típico", pl: "Mój zwykły dzień", uk: "Мій звичайний день" },
      h: {
        en: ["I usually get up at…", "After that I…", "In the evening I like to…"],
        de: ["Ich stehe normalerweise um … auf", "Danach…", "Abends … ich gern"],
        es: ["Normalmente me levanto a las…", "Después…", "Por la noche me gusta…"],
        fr: ["D'habitude, je me lève à…", "Ensuite, je…", "Le soir, j'aime…"],
        it: ["Di solito mi alzo alle…", "Dopo…", "La sera mi piace…"],
        pt: ["Normalmente, acordo às…", "Depois disso, eu…", "À noite, gosto de…"],
        pl: ["Zwykle wstaję o…", "Potem…", "Wieczorem lubię…"],
        uk: ["Зазвичай я прокидаюся о…", "Після цього я…", "Увечері я люблю…"],
      },
    },
    {
      t: { en: "My hobbies", de: "Meine Hobbys", es: "Mis aficiones", fr: "Mes loisirs", it: "I miei hobby", pt: "Meus hobbies", pl: "Moje hobby", uk: "Мої хобі" },
      h: {
        en: ["In my free time I…", "I started … ago", "It makes me feel…"],
        de: ["In meiner Freizeit…", "Ich habe vor … angefangen", "Dabei fühle ich mich…"],
        es: ["En mi tiempo libre…", "Empecé hace…", "Me hace sentir…"],
        fr: ["Pendant mon temps libre, je…", "J'ai commencé il y a…", "Ça me fait me sentir…"],
        it: ["Nel tempo libero…", "Ho iniziato … fa", "Mi fa sentire…"],
        pt: ["No meu tempo livre, eu…", "Comecei há…", "Isso me faz sentir…"],
        pl: ["W wolnym czasie…", "Zacząłem / zaczęłam … temu", "Czuję się wtedy…"],
        uk: ["У вільний час я…", "Я почав / почала … тому", "Це дає мені відчуття…"],
      },
    },
    {
      t: { en: "Weather and seasons", de: "Wetter und Jahreszeiten", es: "El tiempo y las estaciones", fr: "Météo et saisons", it: "Tempo e stagioni", pt: "Tempo e estações", pl: "Pogoda i pory roku", uk: "Погода та пори року" },
      h: {
        en: ["My favourite season is…", "Today the weather is…", "When it rains, I…"],
        de: ["Meine Lieblingsjahreszeit ist…", "Heute ist das Wetter…", "Wenn es regnet…"],
        es: ["Mi estación favorita es…", "Hoy el tiempo está…", "Cuando llueve…"],
        fr: ["Ma saison préférée, c'est…", "Aujourd'hui, il fait…", "Quand il pleut, je…"],
        it: ["La mia stagione preferita è…", "Oggi il tempo è…", "Quando piove…"],
        pt: ["Minha estação favorita é…", "Hoje o tempo está…", "Quando chove, eu…"],
        pl: ["Moja ulubiona pora roku to…", "Dziś pogoda jest…", "Kiedy pada deszcz…"],
        uk: ["Моя улюблена пора року —…", "Сьогодні погода…", "Коли йде дощ, я…"],
      },
    },
    {
      t: { en: "Pets and animals", de: "Haustiere und Tiere", es: "Mascotas y animales", fr: "Les animaux", it: "Gli animali", pt: "Animais de estimação", pl: "Zwierzęta", uk: "Тварини" },
      h: {
        en: ["I have / would like a…", "My pet likes to…", "I think animals…"],
        de: ["Ich habe / hätte gern…", "Mein Haustier mag…", "Ich finde, Tiere…"],
        es: ["Tengo / me gustaría tener…", "A mi mascota le gusta…", "Creo que los animales…"],
        fr: ["J'ai / j'aimerais avoir…", "Mon animal aime…", "Je pense que les animaux…"],
        it: ["Ho / vorrei avere…", "Al mio animale piace…", "Penso che gli animali…"],
        pt: ["Eu tenho / gostaria de ter…", "Meu bichinho gosta de…", "Eu acho que os animais…"],
        pl: ["Mam / chciałbym mieć…", "Moje zwierzę lubi…", "Uważam, że zwierzęta…"],
        uk: ["У мене є / я хотів би…", "Мій улюбленець любить…", "Я думаю, що тварини…"],
      },
    },
    {
      t: { en: "My home", de: "Mein Zuhause", es: "Mi casa", fr: "Chez moi", it: "La mia casa", pt: "Minha casa", pl: "Mój dom", uk: "Мій дім" },
      h: {
        en: ["I live in…", "My favourite room is…", "From my window I can see…"],
        de: ["Ich wohne in…", "Mein Lieblingszimmer ist…", "Aus meinem Fenster sehe ich…"],
        es: ["Vivo en…", "Mi habitación favorita es…", "Desde mi ventana veo…"],
        fr: ["J'habite à…", "Ma pièce préférée, c'est…", "De ma fenêtre, je vois…"],
        it: ["Vivo a…", "La mia stanza preferita è…", "Dalla finestra vedo…"],
        pt: ["Eu moro em…", "Meu cômodo favorito é…", "Da minha janela, eu vejo…"],
        pl: ["Mieszkam w…", "Mój ulubiony pokój to…", "Z okna widzę…"],
        uk: ["Я живу в…", "Моя улюблена кімната —…", "З мого вікна видно…"],
      },
    },
    {
      t: { en: "My friends", de: "Meine Freunde", es: "Mis amigos", fr: "Mes amis", it: "I miei amici", pt: "Meus amigos", pl: "Moi przyjaciele", uk: "Мої друзі" },
      h: {
        en: ["My best friend is called…", "We met…", "Together we usually…"],
        de: ["Mein bester Freund heißt…", "Wir haben uns … kennengelernt", "Zusammen … wir meistens"],
        es: ["Mi mejor amigo se llama…", "Nos conocimos…", "Juntos solemos…"],
        fr: ["Mon meilleur ami s'appelle…", "On s'est rencontrés…", "Ensemble, on…"],
        it: ["Il mio migliore amico si chiama…", "Ci siamo conosciuti…", "Insieme di solito…"],
        pt: ["Meu melhor amigo se chama…", "A gente se conheceu…", "Juntos, normalmente…"],
        pl: ["Mój najlepszy przyjaciel ma na imię…", "Poznaliśmy się…", "Razem zwykle…"],
        uk: ["Мого найкращого друга звати…", "Ми познайомилися…", "Разом ми зазвичай…"],
      },
    },
    {
      t: { en: "School and learning", de: "Schule und Lernen", es: "La escuela", fr: "L'école", it: "La scuola", pt: "Escola e estudos", pl: "Szkoła", uk: "Школа і навчання" },
      h: {
        en: ["I study at…", "My favourite subject is…", "After classes I…"],
        de: ["Ich lerne an…", "Mein Lieblingsfach ist…", "Nach dem Unterricht…"],
        es: ["Estudio en…", "Mi asignatura favorita es…", "Después de las clases…"],
        fr: ["J'étudie à…", "Ma matière préférée, c'est…", "Après les cours, je…"],
        it: ["Studio a…", "La mia materia preferita è…", "Dopo le lezioni…"],
        pt: ["Eu estudo em…", "Minha matéria favorita é…", "Depois das aulas, eu…"],
        pl: ["Uczę się w…", "Mój ulubiony przedmiot to…", "Po lekcjach…"],
        uk: ["Я навчаюся в…", "Мій улюблений предмет —…", "Після занять я…"],
      },
    },
    {
      t: { en: "Music I like", de: "Meine Musik", es: "La música que me gusta", fr: "Ma musique", it: "La mia musica", pt: "Música que eu gosto", pl: "Moja muzyka", uk: "Моя музика" },
      h: {
        en: ["I usually listen to…", "My favourite singer is…", "Music helps me…"],
        de: ["Ich höre meistens…", "Mein Lieblingssänger ist…", "Musik hilft mir…"],
        es: ["Normalmente escucho…", "Mi cantante favorito es…", "La música me ayuda a…"],
        fr: ["J'écoute surtout…", "Mon chanteur préféré, c'est…", "La musique m'aide à…"],
        it: ["Di solito ascolto…", "Il mio cantante preferito è…", "La musica mi aiuta a…"],
        pt: ["Normalmente, eu escuto…", "Meu cantor favorito é…", "A música me ajuda a…"],
        pl: ["Zwykle słucham…", "Mój ulubiony piosenkarz to…", "Muzyka pomaga mi…"],
        uk: ["Зазвичай я слухаю…", "Мій улюблений співак —…", "Музика допомагає мені…"],
      },
    },
    {
      t: { en: "My favourite place", de: "Mein Lieblingsort", es: "Mi lugar favorito", fr: "Mon endroit préféré", it: "Il mio posto preferito", pt: "Meu lugar favorito", pl: "Moje ulubione miejsce", uk: "Моє улюблене місце" },
      h: {
        en: ["My favourite place is…", "I go there when…", "I feel … there"],
        de: ["Mein Lieblingsort ist…", "Ich gehe dorthin, wenn…", "Dort fühle ich mich…"],
        es: ["Mi lugar favorito es…", "Voy allí cuando…", "Allí me siento…"],
        fr: ["Mon endroit préféré, c'est…", "J'y vais quand…", "Là-bas, je me sens…"],
        it: ["Il mio posto preferito è…", "Ci vado quando…", "Lì mi sento…"],
        pt: ["Meu lugar favorito é…", "Eu vou lá quando…", "Lá eu me sinto…"],
        pl: ["Moje ulubione miejsce to…", "Chodzę tam, kiedy…", "Czuję się tam…"],
        uk: ["Моє улюблене місце —…", "Я ходжу туди, коли…", "Там я почуваюся…"],
      },
    },
    {
      t: { en: "Clothes and style", de: "Kleidung und Stil", es: "Ropa y estilo", fr: "Vêtements et style", it: "Vestiti e stile", pt: "Roupas e estilo", pl: "Ubrania i styl", uk: "Одяг і стиль" },
      h: {
        en: ["I usually wear…", "My favourite piece of clothing…", "For me, comfort / style is…"],
        de: ["Ich trage meistens…", "Mein Lieblingskleidungsstück…", "Für mich ist Komfort / Stil…"],
        es: ["Normalmente llevo…", "Mi prenda favorita…", "Para mí, la comodidad / el estilo es…"],
        fr: ["D'habitude, je porte…", "Mon vêtement préféré…", "Pour moi, le confort / le style, c'est…"],
        it: ["Di solito indosso…", "Il mio capo preferito…", "Per me la comodità / lo stile è…"],
        pt: ["Normalmente, eu visto…", "Minha peça de roupa favorita…", "Para mim, conforto / estilo é…"],
        pl: ["Zwykle noszę…", "Moje ulubione ubranie…", "Dla mnie wygoda / styl to…"],
        uk: ["Зазвичай я ношу…", "Моя улюблена річ в одязі…", "Для мене комфорт / стиль — це…"],
      },
    },
    {
      t: { en: "Birthdays", de: "Geburtstage", es: "Los cumpleaños", fr: "Les anniversaires", it: "I compleanni", pt: "Aniversários", pl: "Urodziny", uk: "Дні народження" },
      h: {
        en: ["My birthday is in…", "Last year I celebrated…", "The best gift I got was…"],
        de: ["Mein Geburtstag ist im…", "Letztes Jahr habe ich … gefeiert", "Das beste Geschenk war…"],
        es: ["Mi cumpleaños es en…", "El año pasado celebré…", "El mejor regalo fue…"],
        fr: ["Mon anniversaire est en…", "L'année dernière, j'ai fêté…", "Le meilleur cadeau, c'était…"],
        it: ["Il mio compleanno è a…", "L'anno scorso ho festeggiato…", "Il regalo più bello è stato…"],
        pt: ["Meu aniversário é em…", "No ano passado, eu comemorei…", "O melhor presente que ganhei foi…"],
        pl: ["Moje urodziny są w…", "W zeszłym roku świętowałem…", "Najlepszy prezent to był…"],
        uk: ["Мій день народження у…", "Минулого року я святкував…", "Найкращий подарунок був…"],
      },
    },
    {
      t: { en: "Getting around town", de: "Unterwegs in der Stadt", es: "Moverse por la ciudad", fr: "Se déplacer en ville", it: "Muoversi in città", pt: "Como me locomovo na cidade", pl: "Poruszanie się po mieście", uk: "Як я пересуваюся містом" },
      h: {
        en: ["I usually travel by…", "It takes me … minutes", "I like / don't like buses because…"],
        de: ["Ich fahre meistens mit…", "Ich brauche … Minuten", "Busse mag ich (nicht), weil…"],
        es: ["Normalmente voy en…", "Tardo … minutos", "(No) me gustan los autobuses porque…"],
        fr: ["D'habitude, je me déplace en…", "Ça me prend … minutes", "J'aime / je n'aime pas le bus parce que…"],
        it: ["Di solito mi sposto in…", "Ci metto … minuti", "(Non) mi piacciono gli autobus perché…"],
        pt: ["Normalmente, eu vou de…", "Levo … minutos", "Eu (não) gosto de ônibus porque…"],
        pl: ["Zwykle jeżdżę…", "Zajmuje mi to … minut", "(Nie) lubię autobusów, bo…"],
        uk: ["Зазвичай я їжджу…", "Це займає в мене … хвилин", "Я (не) люблю автобуси, бо…"],
      },
    },
    {
      t: { en: "My weekend", de: "Mein Wochenende", es: "Mi fin de semana", fr: "Mon week-end", it: "Il mio fine settimana", pt: "Meu fim de semana", pl: "Mój weekend", uk: "Мої вихідні" },
      h: {
        en: ["On Saturdays I usually…", "Last weekend I…", "My perfect weekend is…"],
        de: ["Samstags … ich meistens", "Letztes Wochenende habe ich…", "Mein perfektes Wochenende ist…"],
        es: ["Los sábados suelo…", "El fin de semana pasado…", "Mi fin de semana perfecto es…"],
        fr: ["Le samedi, d'habitude, je…", "Le week-end dernier, j'ai…", "Mon week-end parfait, c'est…"],
        it: ["Il sabato di solito…", "Lo scorso fine settimana ho…", "Il mio weekend perfetto è…"],
        pt: ["Aos sábados, normalmente eu…", "No fim de semana passado, eu…", "Meu fim de semana perfeito é…"],
        pl: ["W soboty zwykle…", "W zeszły weekend…", "Mój idealny weekend to…"],
        uk: ["По суботах я зазвичай…", "Минулих вихідних я…", "Мої ідеальні вихідні — це…"],
      },
    },
    {
      t: { en: "Coffee or tea?", de: "Kaffee oder Tee?", es: "¿Café o té?", fr: "Café ou thé ?", it: "Caffè o tè?", pt: "Café ou chá?", pl: "Kawa czy herbata?", uk: "Кава чи чай?" },
      h: {
        en: ["Every morning I drink…", "I prefer … because…", "My favourite café is…"],
        de: ["Jeden Morgen trinke ich…", "Ich mag lieber …, weil…", "Mein Lieblingscafé ist…"],
        es: ["Cada mañana bebo…", "Prefiero … porque…", "Mi cafetería favorita es…"],
        fr: ["Chaque matin, je bois…", "Je préfère … parce que…", "Mon café préféré, c'est…"],
        it: ["Ogni mattina bevo…", "Preferisco … perché…", "Il mio bar preferito è…"],
        pt: ["Toda manhã, eu bebo…", "Eu prefiro … porque…", "Meu café favorito é…"],
        pl: ["Każdego ranka piję…", "Wolę …, bo…", "Moja ulubiona kawiarnia to…"],
        uk: ["Щоранку я п'ю…", "Мені більше смакує …, бо…", "Моя улюблена кав'ярня —…"],
      },
    },
    {
      t: { en: "My city", de: "Meine Stadt", es: "Mi ciudad", fr: "Ma ville", it: "La mia città", pt: "Minha cidade", pl: "Moje miasto", uk: "Моє місто" },
      h: {
        en: ["I live in a city called…", "The best thing about it is…", "Tourists should visit…"],
        de: ["Ich wohne in…", "Das Beste daran ist…", "Touristen sollten … besuchen"],
        es: ["Vivo en una ciudad llamada…", "Lo mejor es…", "Los turistas deberían visitar…"],
        fr: ["J'habite dans une ville qui s'appelle…", "Le mieux, c'est…", "Les touristes devraient visiter…"],
        it: ["Vivo in una città chiamata…", "La cosa migliore è…", "I turisti dovrebbero visitare…"],
        pt: ["Eu moro numa cidade chamada…", "O melhor dela é…", "Os turistas deveriam visitar…"],
        pl: ["Mieszkam w mieście…", "Najlepsze w nim jest…", "Turyści powinni zobaczyć…"],
        uk: ["Я живу в місті…", "Найкраще в ньому —…", "Туристам варто побачити…"],
      },
    },
    {
      t: { en: "Books I read", de: "Bücher", es: "Los libros", fr: "Les livres", it: "I libri", pt: "Livros que eu leio", pl: "Książki", uk: "Книжки" },
      h: {
        en: ["Right now I'm reading…", "My favourite book is…", "I read … a week"],
        de: ["Gerade lese ich…", "Mein Lieblingsbuch ist…", "Ich lese … pro Woche"],
        es: ["Ahora estoy leyendo…", "Mi libro favorito es…", "Leo … a la semana"],
        fr: ["En ce moment, je lis…", "Mon livre préféré, c'est…", "Je lis … par semaine"],
        it: ["In questo momento sto leggendo…", "Il mio libro preferito è…", "Leggo … alla settimana"],
        pt: ["Agora, estou lendo…", "Meu livro favorito é…", "Eu leio … por semana"],
        pl: ["Teraz czytam…", "Moja ulubiona książka to…", "Czytam … tygodniowo"],
        uk: ["Зараз я читаю…", "Моя улюблена книжка —…", "Я читаю … на тиждень"],
      },
    },
    {
      t: { en: "Games I play", de: "Spiele", es: "Los juegos", fr: "Les jeux", it: "I giochi", pt: "Jogos que eu jogo", pl: "Gry", uk: "Ігри" },
      h: {
        en: ["My favourite game is…", "I play with…", "I like it because…"],
        de: ["Mein Lieblingsspiel ist…", "Ich spiele mit…", "Es gefällt mir, weil…"],
        es: ["Mi juego favorito es…", "Juego con…", "Me gusta porque…"],
        fr: ["Mon jeu préféré, c'est…", "Je joue avec…", "J'aime ça parce que…"],
        it: ["Il mio gioco preferito è…", "Gioco con…", "Mi piace perché…"],
        pt: ["Meu jogo favorito é…", "Eu jogo com…", "Eu gosto porque…"],
        pl: ["Moja ulubiona gra to…", "Gram z…", "Lubię ją, bo…"],
        uk: ["Моя улюблена гра —…", "Я граю з…", "Вона подобається мені, бо…"],
      },
    },
    {
      t: { en: "My dream job", de: "Mein Traumberuf", es: "Mi trabajo soñado", fr: "Le métier de mes rêves", it: "Il lavoro dei miei sogni", pt: "O emprego dos meus sonhos", pl: "Praca marzeń", uk: "Робота мрії" },
      h: {
        en: ["When I was small, I wanted to be…", "My dream job is…", "For this job you need…"],
        de: ["Als Kind wollte ich … werden", "Mein Traumberuf ist…", "Für diesen Beruf braucht man…"],
        es: ["De pequeño quería ser…", "Mi trabajo soñado es…", "Para este trabajo se necesita…"],
        fr: ["Petit, je voulais être…", "Le métier de mes rêves, c'est…", "Pour ce métier, il faut…"],
        it: ["Da piccolo volevo fare…", "Il lavoro dei miei sogni è…", "Per questo lavoro serve…"],
        pt: ["Quando eu era pequeno, queria ser…", "O emprego dos meus sonhos é…", "Para esse trabalho, você precisa…"],
        pl: ["Jako dziecko chciałem być…", "Moja praca marzeń to…", "Do tej pracy trzeba…"],
        uk: ["У дитинстві я хотів бути…", "Моя робота мрії —…", "Для цієї роботи потрібно…"],
      },
    },
    {
      t: { en: "Nature around me", de: "Natur um mich", es: "La naturaleza", fr: "La nature", it: "La natura", pt: "A natureza ao meu redor", pl: "Przyroda", uk: "Природа навколо" },
      h: {
        en: ["Near my home there is…", "In summer I like to…", "My favourite flower / tree is…"],
        de: ["In der Nähe meines Hauses gibt es…", "Im Sommer … ich gern", "Meine Lieblingsblume ist…"],
        es: ["Cerca de mi casa hay…", "En verano me gusta…", "Mi flor favorita es…"],
        fr: ["Près de chez moi, il y a…", "En été, j'aime…", "Ma fleur préférée, c'est…"],
        it: ["Vicino a casa mia c'è…", "D'estate mi piace…", "Il mio fiore preferito è…"],
        pt: ["Perto da minha casa, tem…", "No verão, gosto de…", "Minha flor / árvore favorita é…"],
        pl: ["Blisko mojego domu jest…", "Latem lubię…", "Mój ulubiony kwiat to…"],
        uk: ["Біля мого дому є…", "Влітку я люблю…", "Моя улюблена квітка —…"],
      },
    },
    {
      t: { en: "Sleep and rest", de: "Schlaf und Erholung", es: "Dormir y descansar", fr: "Le sommeil", it: "Il sonno", pt: "Sono e descanso", pl: "Sen i odpoczynek", uk: "Сон і відпочинок" },
      h: {
        en: ["I usually sleep … hours", "Before bed I…", "To relax, I…"],
        de: ["Ich schlafe meistens … Stunden", "Vor dem Schlafen…", "Zum Entspannen…"],
        es: ["Normalmente duermo … horas", "Antes de dormir…", "Para relajarme…"],
        fr: ["Je dors en général … heures", "Avant de dormir, je…", "Pour me détendre, je…"],
        it: ["Di solito dormo … ore", "Prima di dormire…", "Per rilassarmi…"],
        pt: ["Normalmente, eu durmo … horas", "Antes de dormir, eu…", "Para relaxar, eu…"],
        pl: ["Zwykle śpię … godzin", "Przed snem…", "Żeby odpocząć…"],
        uk: ["Зазвичай я сплю … годин", "Перед сном я…", "Щоб розслабитися, я…"],
      },
    },
    {
      t: { en: "A happy memory", de: "Eine schöne Erinnerung", es: "Un recuerdo feliz", fr: "Un bon souvenir", it: "Un bel ricordo", pt: "Uma lembrança feliz", pl: "Miłe wspomnienie", uk: "Щасливий спогад" },
      h: {
        en: ["One of my happiest days was…", "It happened in…", "I remember it because…"],
        de: ["Einer meiner schönsten Tage war…", "Es war in…", "Ich erinnere mich daran, weil…"],
        es: ["Uno de mis días más felices fue…", "Pasó en…", "Lo recuerdo porque…"],
        fr: ["Un de mes jours les plus heureux, c'était…", "C'était à…", "Je m'en souviens parce que…"],
        it: ["Uno dei miei giorni più felici è stato…", "È successo a…", "Lo ricordo perché…"],
        pt: ["Um dos meus dias mais felizes foi…", "Aconteceu em…", "Eu me lembro disso porque…"],
        pl: ["Jeden z moich najszczęśliwszych dni to…", "To było w…", "Pamiętam go, bo…"],
        uk: ["Один із моїх найщасливіших днів —…", "Це сталося в…", "Я пам'ятаю його, бо…"],
      },
    },
    {
      t: { en: "My childhood", de: "Meine Kindheit", es: "Mi infancia", fr: "Mon enfance", it: "La mia infanzia", pt: "Minha infância", pl: "Moje dzieciństwo", uk: "Моє дитинство" },
      h: {
        en: ["As a child, I lived in…", "My favourite toy was…", "With my friends we played…"],
        de: ["Als Kind wohnte ich in…", "Mein Lieblingsspielzeug war…", "Mit meinen Freunden spielten wir…"],
        es: ["De niño vivía en…", "Mi juguete favorito era…", "Con mis amigos jugábamos a…"],
        fr: ["Enfant, j'habitais à…", "Mon jouet préféré, c'était…", "Avec mes amis, on jouait à…"],
        it: ["Da bambino vivevo a…", "Il mio giocattolo preferito era…", "Con i miei amici giocavamo a…"],
        pt: ["Quando criança, eu morava em…", "Meu brinquedo favorito era…", "Com meus amigos, a gente brincava de…"],
        pl: ["Jako dziecko mieszkałem w…", "Moją ulubioną zabawką był…", "Z przyjaciółmi graliśmy w…"],
        uk: ["У дитинстві я жив у…", "Моєю улюбленою іграшкою був…", "З друзями ми грали в…"],
      },
    },
  ],

  medium: [
    {
      t: { en: "Travel stories", de: "Reisen", es: "Viajes", fr: "Les voyages", it: "I viaggi", pt: "Histórias de viagem", pl: "Podróże", uk: "Подорожі" },
      h: {
        en: ["The best trip I've ever taken…", "I dream of visiting…", "Travelling teaches you…"],
        de: ["Meine beste Reise war…", "Ich träume davon, … zu besuchen", "Reisen lehrt einen…"],
        es: ["El mejor viaje que he hecho…", "Sueño con visitar…", "Viajar te enseña…"],
        fr: ["Le meilleur voyage que j'ai fait…", "Je rêve de visiter…", "Voyager nous apprend…"],
        it: ["Il viaggio più bello che ho fatto…", "Sogno di visitare…", "Viaggiare ti insegna…"],
        pt: ["A melhor viagem que já fiz…", "Eu sonho em visitar…", "Viajar nos ensina…"],
        pl: ["Najlepsza podróż, jaką odbyłem…", "Marzę o odwiedzeniu…", "Podróże uczą…"],
        uk: ["Найкраща подорож у моєму житті…", "Я мрію відвідати…", "Подорожі вчать нас…"],
      },
    },
    {
      t: { en: "Tech in my life", de: "Technik im Alltag", es: "La tecnología y yo", fr: "La technologie et moi", it: "La tecnologia e io", pt: "A tecnologia na minha vida", pl: "Technologia w moim życiu", uk: "Технології в житті" },
      h: {
        en: ["I spend about … hours online", "The app I couldn't live without…", "Life without the internet would be…"],
        de: ["Ich verbringe etwa … Stunden online", "Die App, ohne die ich nicht leben könnte…", "Ein Leben ohne Internet wäre…"],
        es: ["Paso unas … horas en línea", "La aplicación sin la que no podría vivir…", "La vida sin internet sería…"],
        fr: ["Je passe environ … heures en ligne", "L'appli dont je ne peux pas me passer…", "La vie sans internet serait…"],
        it: ["Passo circa … ore online", "L'app senza cui non potrei vivere…", "La vita senza internet sarebbe…"],
        pt: ["Eu passo cerca de … horas online", "O aplicativo sem o qual eu não vivo…", "A vida sem internet seria…"],
        pl: ["Spędzam około … godzin online", "Aplikacja, bez której nie mogę żyć…", "Życie bez internetu byłoby…"],
        uk: ["Я проводжу близько … годин онлайн", "Додаток, без якого я не можу жити…", "Життя без інтернету було б…"],
      },
    },
    {
      t: { en: "Films and series", de: "Filme und Serien", es: "Cine y series", fr: "Films et séries", it: "Film e serie", pt: "Filmes e séries", pl: "Filmy i seriale", uk: "Фільми та серіали" },
      h: {
        en: ["The last thing I watched was…", "My favourite genre is…", "I'd recommend it because…"],
        de: ["Zuletzt habe ich … gesehen", "Mein Lieblingsgenre ist…", "Ich würde es empfehlen, weil…"],
        es: ["Lo último que vi fue…", "Mi género favorito es…", "Lo recomendaría porque…"],
        fr: ["La dernière chose que j'ai regardée…", "Mon genre préféré, c'est…", "Je le recommanderais parce que…"],
        it: ["L'ultima cosa che ho visto…", "Il mio genere preferito è…", "Lo consiglierei perché…"],
        pt: ["A última coisa que assisti foi…", "Meu gênero favorito é…", "Eu recomendaria porque…"],
        pl: ["Ostatnio obejrzałem…", "Mój ulubiony gatunek to…", "Poleciłbym go, ponieważ…"],
        uk: ["Останнє, що я дивився…", "Мій улюблений жанр —…", "Я б порадив це, бо…"],
      },
    },
    {
      t: { en: "Work and studies", de: "Arbeit und Studium", es: "Trabajo y estudios", fr: "Travail et études", it: "Lavoro e studio", pt: "Trabalho e estudos", pl: "Praca i nauka", uk: "Робота та навчання" },
      h: {
        en: ["At the moment I work / study…", "The most difficult part is…", "In five years I hope to…"],
        de: ["Zurzeit arbeite / studiere ich…", "Am schwierigsten ist…", "In fünf Jahren hoffe ich…"],
        es: ["Actualmente trabajo / estudio…", "Lo más difícil es…", "En cinco años espero…"],
        fr: ["En ce moment, je travaille / j'étudie…", "Le plus difficile, c'est…", "Dans cinq ans, j'espère…"],
        it: ["Al momento lavoro / studio…", "La parte più difficile è…", "Tra cinque anni spero di…"],
        pt: ["No momento, eu trabalho / estudo…", "A parte mais difícil é…", "Em cinco anos, espero…"],
        pl: ["Obecnie pracuję / studiuję…", "Najtrudniejsze jest…", "Za pięć lat mam nadzieję…"],
        uk: ["Зараз я працюю / навчаюся…", "Найважче — це…", "Через п'ять років я сподіваюся…"],
      },
    },
    {
      t: { en: "Sport and health", de: "Sport und Gesundheit", es: "Deporte y salud", fr: "Sport et santé", it: "Sport e salute", pt: "Esporte e saúde", pl: "Sport i zdrowie", uk: "Спорт і здоров'я" },
      h: {
        en: ["To stay healthy, I try to…", "I play / used to play…", "The hardest habit for me is…"],
        de: ["Um gesund zu bleiben, versuche ich…", "Ich spiele / habe … gespielt", "Die schwierigste Gewohnheit ist…"],
        es: ["Para mantenerme sano, intento…", "Juego / solía jugar…", "El hábito más difícil para mí es…"],
        fr: ["Pour rester en forme, j'essaie de…", "Je fais / je faisais…", "L'habitude la plus difficile, c'est…"],
        it: ["Per restare in salute cerco di…", "Gioco / giocavo a…", "L'abitudine più difficile per me è…"],
        pt: ["Para me manter saudável, eu tento…", "Eu jogo / jogava…", "O hábito mais difícil para mim é…"],
        pl: ["Żeby być zdrowym, staram się…", "Gram / grałem w…", "Najtrudniejszy nawyk to…"],
        uk: ["Щоб бути здоровим, я намагаюся…", "Я займаюся / займався…", "Найважча звичка для мене —…"],
      },
    },
    {
      t: { en: "Holidays and traditions", de: "Feste und Traditionen", es: "Fiestas y tradiciones", fr: "Fêtes et traditions", it: "Feste e tradizioni", pt: "Feriados e tradições", pl: "Święta i tradycje", uk: "Свята і традиції" },
      h: {
        en: ["My favourite holiday is…", "In my family we always…", "A tradition I love is…"],
        de: ["Mein Lieblingsfest ist…", "In meiner Familie … wir immer", "Eine Tradition, die ich liebe…"],
        es: ["Mi fiesta favorita es…", "En mi familia siempre…", "Una tradición que me encanta…"],
        fr: ["Ma fête préférée, c'est…", "Dans ma famille, on … toujours", "Une tradition que j'adore…"],
        it: ["La mia festa preferita è…", "Nella mia famiglia … sempre", "Una tradizione che amo…"],
        pt: ["Meu feriado favorito é…", "Na minha família, a gente sempre…", "Uma tradição que eu amo é…"],
        pl: ["Moje ulubione święto to…", "W mojej rodzinie zawsze…", "Tradycja, którą kocham…"],
        uk: ["Моє улюблене свято —…", "У моїй родині ми завжди…", "Традиція, яку я люблю, —…"],
      },
    },
    {
      t: { en: "Shopping habits", de: "Einkaufen", es: "De compras", fr: "Le shopping", it: "Fare acquisti", pt: "Hábitos de compra", pl: "Zakupy", uk: "Покупки" },
      h: {
        en: ["I prefer shopping online / in shops because…", "The last thing I bought was…", "I never spend money on…"],
        de: ["Ich kaufe lieber online / im Laden, weil…", "Zuletzt habe ich … gekauft", "Ich gebe nie Geld für … aus"],
        es: ["Prefiero comprar en línea / en tiendas porque…", "Lo último que compré fue…", "Nunca gasto dinero en…"],
        fr: ["Je préfère acheter en ligne / en magasin parce que…", "La dernière chose que j'ai achetée…", "Je ne dépense jamais d'argent pour…"],
        it: ["Preferisco comprare online / nei negozi perché…", "L'ultima cosa che ho comprato…", "Non spendo mai soldi per…"],
        pt: ["Eu prefiro comprar online / em lojas porque…", "A última coisa que comprei foi…", "Eu nunca gasto dinheiro com…"],
        pl: ["Wolę kupować online / w sklepach, bo…", "Ostatnio kupiłem…", "Nigdy nie wydaję pieniędzy na…"],
        uk: ["Мені більше подобається купувати онлайн / у магазинах, бо…", "Останнє, що я купив, —…", "Я ніколи не витрачаю гроші на…"],
      },
    },
    {
      t: { en: "Plans and dreams", de: "Pläne und Träume", es: "Planes y sueños", fr: "Projets et rêves", it: "Progetti e sogni", pt: "Planos e sonhos", pl: "Plany i marzenia", uk: "Плани та мрії" },
      h: {
        en: ["My biggest dream is…", "Next year I'm planning to…", "To achieve it, I need to…"],
        de: ["Mein größter Traum ist…", "Nächstes Jahr plane ich…", "Um das zu erreichen, muss ich…"],
        es: ["Mi mayor sueño es…", "El año que viene pienso…", "Para lograrlo, necesito…"],
        fr: ["Mon plus grand rêve, c'est…", "L'année prochaine, je compte…", "Pour y arriver, je dois…"],
        it: ["Il mio sogno più grande è…", "L'anno prossimo ho intenzione di…", "Per riuscirci devo…"],
        pt: ["Meu maior sonho é…", "No ano que vem, pretendo…", "Para conseguir isso, eu preciso…"],
        pl: ["Moje największe marzenie to…", "W przyszłym roku planuję…", "Aby to osiągnąć, muszę…"],
        uk: ["Моя найбільша мрія —…", "Наступного року я планую…", "Щоб цього досягти, мені треба…"],
      },
    },
    {
      t: { en: "Cooking and recipes", de: "Kochen und Rezepte", es: "Cocinar y recetas", fr: "Cuisine et recettes", it: "Cucina e ricette", pt: "Cozinha e receitas", pl: "Gotowanie", uk: "Кулінарія" },
      h: {
        en: ["The dish I cook best is…", "I learned it from…", "The secret ingredient is…"],
        de: ["Am besten koche ich…", "Gelernt habe ich es von…", "Die geheime Zutat ist…"],
        es: ["El plato que mejor cocino es…", "Lo aprendí de…", "El ingrediente secreto es…"],
        fr: ["Le plat que je réussis le mieux…", "Je l'ai appris de…", "L'ingrédient secret, c'est…"],
        it: ["Il piatto che cucino meglio è…", "L'ho imparato da…", "L'ingrediente segreto è…"],
        pt: ["O prato que eu cozinho melhor é…", "Aprendi com…", "O ingrediente secreto é…"],
        pl: ["Danie, które gotuję najlepiej, to…", "Nauczyłem się go od…", "Sekretny składnik to…"],
        uk: ["Страва, яка вдається мені найкраще, —…", "Я навчився її від…", "Секретний інгредієнт —…"],
      },
    },
    {
      t: { en: "Learning languages", de: "Sprachen lernen", es: "Aprender idiomas", fr: "Apprendre les langues", it: "Imparare le lingue", pt: "Aprender idiomas", pl: "Nauka języków", uk: "Вивчення мов" },
      h: {
        en: ["I've been learning … for…", "The hardest part for me is…", "My method is to…"],
        de: ["Ich lerne … seit…", "Am schwersten fällt mir…", "Meine Methode ist…"],
        es: ["Llevo … aprendiendo…", "Lo más difícil para mí es…", "Mi método es…"],
        fr: ["J'apprends … depuis…", "Le plus dur pour moi, c'est…", "Ma méthode, c'est de…"],
        it: ["Studio … da…", "La cosa più difficile per me è…", "Il mio metodo è…"],
        pt: ["Estou aprendendo … há…", "A parte mais difícil para mim é…", "Meu método é…"],
        pl: ["Uczę się … od…", "Najtrudniejsze dla mnie jest…", "Moja metoda to…"],
        uk: ["Я вивчаю … вже…", "Найважче для мене —…", "Мій метод — це…"],
      },
    },
    {
      t: { en: "Saving and spending", de: "Sparen und Ausgeben", es: "Ahorrar y gastar", fr: "Épargner et dépenser", it: "Risparmiare e spendere", pt: "Poupar e gastar", pl: "Oszczędzanie i wydawanie", uk: "Заощадження і витрати" },
      h: {
        en: ["I'm good / bad at saving because…", "Most of my money goes on…", "My advice about money is…"],
        de: ["Ich kann (nicht) gut sparen, weil…", "Das meiste Geld gebe ich für … aus", "Mein Rat zum Thema Geld:…"],
        es: ["Se me da bien / mal ahorrar porque…", "La mayor parte de mi dinero va a…", "Mi consejo sobre el dinero es…"],
        fr: ["Je sais / je ne sais pas épargner parce que…", "La plupart de mon argent part dans…", "Mon conseil sur l'argent :…"],
        it: ["So / non so risparmiare perché…", "La maggior parte dei miei soldi va in…", "Il mio consiglio sui soldi è…"],
        pt: ["Eu sou bom / ruim em poupar porque…", "A maior parte do meu dinheiro vai para…", "Meu conselho sobre dinheiro é…"],
        pl: ["Umiem / nie umiem oszczędzać, bo…", "Większość pieniędzy wydaję na…", "Moja rada w sprawie pieniędzy:…"],
        uk: ["Я вмію / не вмію заощаджувати, бо…", "Більшість грошей у мене йде на…", "Моя порада щодо грошей:…"],
      },
    },
    {
      t: { en: "Following the news", de: "Nachrichten verfolgen", es: "Seguir las noticias", fr: "Suivre l'actualité", it: "Seguire le notizie", pt: "Acompanhar as notícias", pl: "Śledzenie wiadomości", uk: "Як я стежу за новинами" },
      h: {
        en: ["I get my news from…", "I check the news … times a day", "Too much news makes me…"],
        de: ["Meine Nachrichten bekomme ich von…", "Ich schaue … Mal am Tag nach", "Zu viele Nachrichten machen mich…"],
        es: ["Me informo por…", "Miro las noticias … veces al día", "Demasiadas noticias me hacen…"],
        fr: ["Je m'informe via…", "Je regarde les infos … fois par jour", "Trop d'infos me rendent…"],
        it: ["Mi informo tramite…", "Controllo le notizie … volte al giorno", "Troppe notizie mi rendono…"],
        pt: ["Eu me informo por…", "Eu vejo as notícias … vezes por dia", "Notícias demais me deixam…"],
        pl: ["Wiadomości czerpię z…", "Sprawdzam newsy … razy dziennie", "Nadmiar wiadomości sprawia, że…"],
        uk: ["Новини я дізнаюся з…", "Я перевіряю новини … разів на день", "Забагато новин робить мене…"],
      },
    },
    {
      t: { en: "Building better habits", de: "Bessere Gewohnheiten", es: "Mejorar mis hábitos", fr: "De meilleures habitudes", it: "Abitudini migliori", pt: "Criar hábitos melhores", pl: "Lepsze nawyki", uk: "Кращі звички" },
      h: {
        en: ["A habit I'm proud of is…", "I'm trying to stop…", "What helps me most is…"],
        de: ["Eine Gewohnheit, auf die ich stolz bin…", "Ich versuche, mit … aufzuhören", "Am meisten hilft mir…"],
        es: ["Un hábito del que estoy orgulloso…", "Intento dejar de…", "Lo que más me ayuda es…"],
        fr: ["Une habitude dont je suis fier…", "J'essaie d'arrêter de…", "Ce qui m'aide le plus, c'est…"],
        it: ["Un'abitudine di cui sono fiero…", "Sto cercando di smettere di…", "Ciò che mi aiuta di più è…"],
        pt: ["Um hábito do qual tenho orgulho é…", "Estou tentando parar de…", "O que mais me ajuda é…"],
        pl: ["Nawyk, z którego jestem dumny…", "Próbuję przestać…", "Najbardziej pomaga mi…"],
        uk: ["Звичка, якою я пишаюся, —…", "Я намагаюся припинити…", "Найбільше мені допомагає…"],
      },
    },
    {
      t: { en: "Giving and receiving gifts", de: "Geschenke", es: "Los regalos", fr: "Les cadeaux", it: "I regali", pt: "Dar e receber presentes", pl: "Prezenty", uk: "Подарунки" },
      h: {
        en: ["The best gift I ever gave…", "I find choosing gifts…", "Money as a gift is…"],
        de: ["Das beste Geschenk, das ich je gemacht habe…", "Geschenke auszusuchen finde ich…", "Geld als Geschenk ist…"],
        es: ["El mejor regalo que he hecho…", "Elegir regalos me parece…", "El dinero como regalo es…"],
        fr: ["Le meilleur cadeau que j'ai offert…", "Choisir un cadeau, je trouve ça…", "L'argent comme cadeau, c'est…"],
        it: ["Il regalo più bello che ho fatto…", "Scegliere i regali lo trovo…", "I soldi come regalo sono…"],
        pt: ["O melhor presente que já dei…", "Escolher presentes eu acho…", "Dinheiro de presente é…"],
        pl: ["Najlepszy prezent, jaki dałem…", "Wybieranie prezentów uważam za…", "Pieniądze jako prezent to…"],
        uk: ["Найкращий подарунок, який я дарував…", "Обирати подарунки для мене…", "Гроші як подарунок — це…"],
      },
    },
    {
      t: { en: "Living abroad", de: "Leben im Ausland", es: "Vivir en el extranjero", fr: "Vivre à l'étranger", it: "Vivere all'estero", pt: "Morar no exterior", pl: "Życie za granicą", uk: "Життя за кордоном" },
      h: {
        en: ["I would / wouldn't move abroad because…", "The hardest thing would be…", "A country I could live in is…"],
        de: ["Ich würde (nicht) ins Ausland ziehen, weil…", "Am schwersten wäre…", "Ein Land, in dem ich leben könnte…"],
        es: ["Me mudaría / no me mudaría porque…", "Lo más difícil sería…", "Un país donde podría vivir es…"],
        fr: ["Je partirais / ne partirais pas parce que…", "Le plus dur serait…", "Un pays où je pourrais vivre…"],
        it: ["Mi trasferirei / non mi trasferirei perché…", "La cosa più difficile sarebbe…", "Un paese dove potrei vivere è…"],
        pt: ["Eu me mudaria / não me mudaria porque…", "A coisa mais difícil seria…", "Um país onde eu poderia viver é…"],
        pl: ["Przeprowadziłbym się / nie przeprowadziłbym się, bo…", "Najtrudniejsze byłoby…", "Kraj, w którym mógłbym żyć, to…"],
        uk: ["Я б переїхав / не переїхав, бо…", "Найважчим було б…", "Країна, де я міг би жити, —…"],
      },
    },
    {
      t: { en: "Someone who inspires me", de: "Jemand, der mich inspiriert", es: "Alguien que me inspira", fr: "Quelqu'un qui m'inspire", it: "Qualcuno che mi ispira", pt: "Alguém que me inspira", pl: "Ktoś, kto mnie inspiruje", uk: "Людина, яка мене надихає" },
      h: {
        en: ["A person I really admire is…", "What impresses me about them…", "Thanks to them, I…"],
        de: ["Eine Person, die ich bewundere, ist…", "Was mich an ihr beeindruckt…", "Dank ihr habe ich…"],
        es: ["Una persona que admiro es…", "Lo que me impresiona de ella…", "Gracias a ella, yo…"],
        fr: ["Une personne que j'admire, c'est…", "Ce qui m'impressionne chez elle…", "Grâce à elle, je…"],
        it: ["Una persona che ammiro è…", "Ciò che mi colpisce di lei…", "Grazie a lei, io…"],
        pt: ["Uma pessoa que eu admiro muito é…", "O que me impressiona nela…", "Graças a ela, eu…"],
        pl: ["Osoba, którą podziwiam, to…", "To, co mnie w niej zachwyca…", "Dzięki niej ja…"],
        uk: ["Людина, якою я захоплююся, —…", "Мене вражає в ній…", "Завдяки їй я…"],
      },
    },
    {
      t: { en: "Becoming an adult", de: "Erwachsenwerden", es: "Hacerse adulto", fr: "Devenir adulte", it: "Diventare adulti", pt: "Tornar-se adulto", pl: "Dorastanie", uk: "Дорослішання" },
      h: {
        en: ["Being an adult means…", "The best part of growing up…", "I miss … from being a kid"],
        de: ["Erwachsen sein bedeutet…", "Das Beste am Erwachsenwerden…", "Aus der Kindheit vermisse ich…"],
        es: ["Ser adulto significa…", "Lo mejor de crecer…", "Echo de menos … de la infancia"],
        fr: ["Être adulte, ça veut dire…", "Le meilleur côté de grandir…", "De l'enfance, ce qui me manque…"],
        it: ["Essere adulti significa…", "La parte migliore del crescere…", "Dell'infanzia mi manca…"],
        pt: ["Ser adulto significa…", "A melhor parte de crescer…", "Eu sinto falta de … da infância"],
        pl: ["Bycie dorosłym oznacza…", "Najlepsze w dorastaniu…", "Z dzieciństwa brakuje mi…"],
        uk: ["Бути дорослим означає…", "Найкраще в дорослішанні…", "З дитинства мені бракує…"],
      },
    },
    {
      t: { en: "Facing my fears", de: "Meine Ängste", es: "Mis miedos", fr: "Mes peurs", it: "Le mie paure", pt: "Enfrentar meus medos", pl: "Moje lęki", uk: "Мої страхи" },
      h: {
        en: ["I'm most afraid of…", "It started when…", "To deal with it, I…"],
        de: ["Am meisten habe ich Angst vor…", "Es begann, als…", "Um damit umzugehen, …"],
        es: ["A lo que más temo es…", "Empezó cuando…", "Para afrontarlo, yo…"],
        fr: ["Ce qui me fait le plus peur, c'est…", "Ça a commencé quand…", "Pour y faire face, je…"],
        it: ["Ho più paura di…", "È iniziato quando…", "Per affrontarla, io…"],
        pt: ["Eu tenho mais medo de…", "Começou quando…", "Para lidar com isso, eu…"],
        pl: ["Najbardziej boję się…", "Zaczęło się, gdy…", "Żeby sobie z tym radzić, ja…"],
        uk: ["Найбільше я боюся…", "Це почалося, коли…", "Щоб упоратися з цим, я…"],
      },
    },
    {
      t: { en: "My perfect day", de: "Mein perfekter Tag", es: "Mi día perfecto", fr: "Ma journée parfaite", it: "La mia giornata perfetta", pt: "Meu dia perfeito", pl: "Mój idealny dzień", uk: "Мій ідеальний день" },
      h: {
        en: ["My perfect day would start with…", "Then I would…", "In the evening…"],
        de: ["Mein perfekter Tag würde mit … beginnen", "Dann würde ich…", "Am Abend…"],
        es: ["Mi día perfecto empezaría con…", "Luego…", "Por la noche…"],
        fr: ["Ma journée parfaite commencerait par…", "Ensuite, je…", "Le soir…"],
        it: ["La mia giornata perfetta inizierebbe con…", "Poi…", "La sera…"],
        pt: ["Meu dia perfeito começaria com…", "Depois, eu…", "À noite…"],
        pl: ["Mój idealny dzień zacząłby się od…", "Potem…", "Wieczorem…"],
        uk: ["Мій ідеальний день почався б із…", "Потім я б…", "Увечері…"],
      },
    },
    {
      t: { en: "Does appearance matter?", de: "Ist Aussehen wichtig?", es: "¿Importa la apariencia?", fr: "L'apparence compte-t-elle ?", it: "L'aspetto conta?", pt: "A aparência importa?", pl: "Czy wygląd ma znaczenie?", uk: "Чи важлива зовнішність?" },
      h: {
        en: ["First impressions are…", "In my experience, looks…", "More important than appearance is…"],
        de: ["Der erste Eindruck ist…", "Meiner Erfahrung nach ist Aussehen…", "Wichtiger als Aussehen ist…"],
        es: ["La primera impresión es…", "En mi experiencia, el aspecto…", "Más importante que la apariencia es…"],
        fr: ["La première impression est…", "D'après mon expérience, le physique…", "Plus important que l'apparence, c'est…"],
        it: ["La prima impressione è…", "Nella mia esperienza, l'aspetto…", "Più importante dell'aspetto è…"],
        pt: ["A primeira impressão é…", "Na minha experiência, a aparência…", "Mais importante que a aparência é…"],
        pl: ["Pierwsze wrażenie jest…", "Z mojego doświadczenia wygląd…", "Ważniejsze od wyglądu jest…"],
        uk: ["Перше враження —…", "З мого досвіду, зовнішність…", "Важливіше за зовнішність —…"],
      },
    },
    {
      t: { en: "Concerts and live events", de: "Konzerte und Events", es: "Conciertos y eventos", fr: "Concerts et événements", it: "Concerti ed eventi", pt: "Shows e eventos ao vivo", pl: "Koncerty i wydarzenia", uk: "Концерти та події" },
      h: {
        en: ["The best event I've been to…", "Live music feels…", "Tickets today cost…"],
        de: ["Das beste Event, auf dem ich war…", "Livemusik fühlt sich … an", "Tickets kosten heute…"],
        es: ["El mejor evento al que he ido…", "La música en vivo se siente…", "Las entradas hoy cuestan…"],
        fr: ["Le meilleur événement où je suis allé…", "La musique live, c'est…", "Les billets coûtent aujourd'hui…"],
        it: ["Il miglior evento a cui sono stato…", "La musica dal vivo è…", "I biglietti oggi costano…"],
        pt: ["O melhor evento em que estive…", "Música ao vivo é…", "Os ingressos hoje custam…"],
        pl: ["Najlepsze wydarzenie, na jakim byłem…", "Muzyka na żywo jest…", "Bilety dziś kosztują…"],
        uk: ["Найкраща подія, на якій я був…", "Жива музика — це…", "Квитки сьогодні коштують…"],
      },
    },
    {
      t: { en: "Living alone or with others", de: "Allein oder zusammen wohnen", es: "¿Vivir solo o acompañado?", fr: "Vivre seul ou à plusieurs", it: "Vivere da soli o in compagnia", pt: "Morar sozinho ou com outras pessoas", pl: "Mieszkać samemu czy z kimś", uk: "Жити самому чи з кимось" },
      h: {
        en: ["Right now I live…", "The advantage of living alone…", "Sharing a flat teaches you…"],
        de: ["Zurzeit wohne ich…", "Der Vorteil des Alleinwohnens…", "Eine WG lehrt einen…"],
        es: ["Ahora vivo…", "La ventaja de vivir solo…", "Compartir piso te enseña…"],
        fr: ["En ce moment, je vis…", "L'avantage de vivre seul…", "La colocation t'apprend…"],
        it: ["Al momento vivo…", "Il vantaggio di vivere da soli…", "Condividere casa ti insegna…"],
        pt: ["No momento, eu moro…", "A vantagem de morar sozinho…", "Dividir apartamento ensina…"],
        pl: ["Teraz mieszkam…", "Zaletą mieszkania samemu…", "Mieszkanie z kimś uczy…"],
        uk: ["Зараз я живу…", "Перевага життя наодинці…", "Життя зі співмешканцями вчить…"],
      },
    },
    {
      t: { en: "Fighting procrastination", de: "Kampf dem Aufschieben", es: "Vencer la procrastinación", fr: "Vaincre la procrastination", it: "Vincere la procrastinazione", pt: "Combater a procrastinação", pl: "Walka z prokrastynacją", uk: "Боротьба з прокрастинацією" },
      h: {
        en: ["I usually put off…", "My trick to start is…", "Deadlines make me…"],
        de: ["Ich schiebe meistens … auf", "Mein Trick, um anzufangen…", "Deadlines machen mich…"],
        es: ["Suelo aplazar…", "Mi truco para empezar es…", "Las fechas límite me hacen…"],
        fr: ["Je remets souvent … à plus tard", "Mon astuce pour commencer…", "Les deadlines me rendent…"],
        it: ["Di solito rimando…", "Il mio trucco per iniziare è…", "Le scadenze mi rendono…"],
        pt: ["Eu costumo adiar…", "Meu truque para começar é…", "Prazos me deixam…"],
        pl: ["Zwykle odkładam…", "Mój trik, żeby zacząć, to…", "Terminy sprawiają, że…"],
        uk: ["Зазвичай я відкладаю…", "Мій трюк, щоб почати, —…", "Дедлайни роблять мене…"],
      },
    },
    {
      t: { en: "What is success?", de: "Was ist Erfolg?", es: "¿Qué es el éxito?", fr: "C'est quoi, la réussite ?", it: "Cos'è il successo?", pt: "O que é sucesso?", pl: "Czym jest sukces?", uk: "Що таке успіх?" },
      h: {
        en: ["For me, success means…", "Society says success is…", "A successful person I know…"],
        de: ["Für mich bedeutet Erfolg…", "Die Gesellschaft sagt, Erfolg ist…", "Ein erfolgreicher Mensch, den ich kenne…"],
        es: ["Para mí, el éxito significa…", "La sociedad dice que el éxito es…", "Una persona exitosa que conozco…"],
        fr: ["Pour moi, réussir, c'est…", "La société dit que la réussite, c'est…", "Une personne accomplie que je connais…"],
        it: ["Per me il successo significa…", "La società dice che il successo è…", "Una persona di successo che conosco…"],
        pt: ["Para mim, sucesso significa…", "A sociedade diz que sucesso é…", "Uma pessoa de sucesso que eu conheço…"],
        pl: ["Dla mnie sukces oznacza…", "Społeczeństwo mówi, że sukces to…", "Osoba sukcesu, którą znam…"],
        uk: ["Для мене успіх означає…", "Суспільство каже, що успіх — це…", "Успішна людина, яку я знаю…"],
      },
    },
  ],

  hard: [
    {
      t: { en: "Social media: good or evil?", de: "Soziale Medien: Fluch oder Segen?", es: "Redes sociales: ¿bien o mal?", fr: "Réseaux sociaux : bien ou mal ?", it: "Social: bene o male?", pt: "Redes sociais: bem ou mal?", pl: "Media społecznościowe: dobro czy zło?", uk: "Соцмережі: добро чи зло?" },
      h: {
        en: ["On the one hand, social media…", "Studies suggest that…", "If I could change one thing…"],
        de: ["Einerseits…, andererseits…", "Studien zeigen, dass…", "Wenn ich eine Sache ändern könnte…"],
        es: ["Por un lado…, por otro…", "Los estudios sugieren que…", "Si pudiera cambiar una cosa…"],
        fr: ["D'un côté…, de l'autre…", "Des études montrent que…", "Si je pouvais changer une chose…"],
        it: ["Da un lato…, dall'altro…", "Gli studi suggeriscono che…", "Se potessi cambiare una cosa…"],
        pt: ["Por um lado, as redes sociais…", "Estudos sugerem que…", "Se eu pudesse mudar uma coisa…"],
        pl: ["Z jednej strony…, z drugiej…", "Badania sugerują, że…", "Gdybym mógł zmienić jedną rzecz…"],
        uk: ["З одного боку…, з іншого…", "Дослідження показують, що…", "Якби я міг змінити одну річ…"],
      },
    },
    {
      t: { en: "Climate change", de: "Klimawandel", es: "El cambio climático", fr: "Le changement climatique", it: "Il cambiamento climatico", pt: "Mudança climática", pl: "Zmiany klimatu", uk: "Зміни клімату" },
      h: {
        en: ["The main cause is…", "Governments should…", "On a personal level, I…"],
        de: ["Die Hauptursache ist…", "Die Regierungen sollten…", "Ich persönlich…"],
        es: ["La causa principal es…", "Los gobiernos deberían…", "A nivel personal, yo…"],
        fr: ["La cause principale est…", "Les gouvernements devraient…", "À titre personnel, je…"],
        it: ["La causa principale è…", "I governi dovrebbero…", "A livello personale, io…"],
        pt: ["A principal causa é…", "Os governos deveriam…", "No nível pessoal, eu…"],
        pl: ["Główną przyczyną jest…", "Rządy powinny…", "Osobiście…"],
        uk: ["Головна причина —…", "Уряди повинні…", "Особисто я…"],
      },
    },
    {
      t: { en: "AI and the future of work", de: "KI und die Zukunft der Arbeit", es: "La IA y el futuro del trabajo", fr: "L'IA et l'avenir du travail", it: "L'IA e il futuro del lavoro", pt: "IA e o futuro do trabalho", pl: "AI i przyszłość pracy", uk: "ШІ та майбутнє роботи" },
      h: {
        en: ["AI is already able to…", "Jobs that may disappear…", "However, humans will still…"],
        de: ["KI kann bereits…", "Berufe, die verschwinden könnten…", "Trotzdem werden Menschen…"],
        es: ["La IA ya es capaz de…", "Los trabajos que podrían desaparecer…", "Sin embargo, los humanos…"],
        fr: ["L'IA est déjà capable de…", "Les métiers qui pourraient disparaître…", "Cependant, les humains…"],
        it: ["L'IA è già in grado di…", "I lavori che potrebbero sparire…", "Tuttavia, gli esseri umani…"],
        pt: ["A IA já é capaz de…", "Empregos que podem desaparecer…", "Ainda assim, os humanos…"],
        pl: ["AI już potrafi…", "Zawody, które mogą zniknąć…", "Jednak ludzie nadal…"],
        uk: ["ШІ вже вміє…", "Професії, які можуть зникнути…", "Проте люди все одно…"],
      },
    },
    {
      t: { en: "How education should change", de: "Wie sich Bildung ändern muss", es: "Cómo debe cambiar la educación", fr: "Comment l'école doit changer", it: "Come deve cambiare la scuola", pt: "Como a educação deveria mudar", pl: "Jak zmienić edukację", uk: "Якою має бути освіта" },
      h: {
        en: ["The current system fails to…", "Instead of exams, we should…", "The most valuable skill today is…"],
        de: ["Das heutige System schafft es nicht…", "Statt Prüfungen sollten wir…", "Die wichtigste Fähigkeit heute ist…"],
        es: ["El sistema actual no logra…", "En lugar de exámenes, deberíamos…", "La habilidad más valiosa hoy es…"],
        fr: ["Le système actuel ne parvient pas à…", "Au lieu des examens, on devrait…", "La compétence la plus précieuse aujourd'hui…"],
        it: ["Il sistema attuale non riesce a…", "Invece degli esami dovremmo…", "La competenza più preziosa oggi è…"],
        pt: ["O sistema atual não consegue…", "Em vez de provas, deveríamos…", "A habilidade mais valiosa hoje é…"],
        pl: ["Obecny system nie potrafi…", "Zamiast egzaminów powinniśmy…", "Najcenniejsza umiejętność dziś to…"],
        uk: ["Теперішня система не здатна…", "Замість іспитів варто було б…", "Найцінніша навичка сьогодні —…"],
      },
    },
    {
      t: { en: "Does money buy happiness?", de: "Macht Geld glücklich?", es: "¿El dinero da la felicidad?", fr: "L'argent fait-il le bonheur ?", it: "I soldi fanno la felicità?", pt: "Dinheiro compra felicidade?", pl: "Czy pieniądze dają szczęście?", uk: "Чи щастя в грошах?" },
      h: {
        en: ["Up to a point, money…", "Research shows that…", "In my own experience…"],
        de: ["Bis zu einem gewissen Punkt…", "Die Forschung zeigt, dass…", "Meiner Erfahrung nach…"],
        es: ["Hasta cierto punto, el dinero…", "Las investigaciones muestran que…", "En mi experiencia…"],
        fr: ["Jusqu'à un certain point, l'argent…", "La recherche montre que…", "D'après mon expérience…"],
        it: ["Fino a un certo punto, i soldi…", "La ricerca mostra che…", "Nella mia esperienza…"],
        pt: ["Até certo ponto, o dinheiro…", "Pesquisas mostram que…", "Na minha própria experiência…"],
        pl: ["Do pewnego stopnia pieniądze…", "Badania pokazują, że…", "Z mojego doświadczenia…"],
        uk: ["До певної межі гроші…", "Дослідження показують, що…", "З мого досвіду…"],
      },
    },
    {
      t: { en: "City vs countryside", de: "Stadt oder Land?", es: "¿Ciudad o campo?", fr: "Ville ou campagne ?", it: "Città o campagna?", pt: "Cidade ou campo?", pl: "Miasto czy wieś?", uk: "Місто чи село?" },
      h: {
        en: ["The main advantage of city life…", "On the other hand, the countryside…", "Personally, I would choose…"],
        de: ["Der größte Vorteil der Stadt…", "Andererseits bietet das Land…", "Ich persönlich würde … wählen"],
        es: ["La mayor ventaja de la ciudad…", "Por otro lado, el campo…", "Personalmente, elegiría…"],
        fr: ["Le grand avantage de la ville…", "En revanche, la campagne…", "Personnellement, je choisirais…"],
        it: ["Il grande vantaggio della città…", "D'altra parte, la campagna…", "Personalmente sceglierei…"],
        pt: ["A principal vantagem da cidade…", "Por outro lado, o campo…", "Pessoalmente, eu escolheria…"],
        pl: ["Główną zaletą miasta…", "Z drugiej strony wieś…", "Osobiście wybrałbym…"],
        uk: ["Головна перевага міста —…", "З іншого боку, село…", "Особисто я обрав би…"],
      },
    },
    {
      t: { en: "Why art matters", de: "Warum Kunst wichtig ist", es: "Por qué importa el arte", fr: "Pourquoi l'art compte", it: "Perché l'arte conta", pt: "Por que a arte importa", pl: "Dlaczego sztuka jest ważna", uk: "Навіщо нам мистецтво" },
      h: {
        en: ["Art allows us to…", "A society without art would…", "A work that really moved me…"],
        de: ["Kunst ermöglicht es uns…", "Eine Gesellschaft ohne Kunst wäre…", "Ein Werk, das mich berührt hat…"],
        es: ["El arte nos permite…", "Una sociedad sin arte sería…", "Una obra que me conmovió…"],
        fr: ["L'art nous permet de…", "Une société sans art serait…", "Une œuvre qui m'a touché…"],
        it: ["L'arte ci permette di…", "Una società senza arte sarebbe…", "Un'opera che mi ha commosso…"],
        pt: ["A arte nos permite…", "Uma sociedade sem arte seria…", "Uma obra que me emocionou…"],
        pl: ["Sztuka pozwala nam…", "Społeczeństwo bez sztuki byłoby…", "Dzieło, które mnie poruszyło…"],
        uk: ["Мистецтво дозволяє нам…", "Суспільство без мистецтва було б…", "Твір, який мене вразив, —…"],
      },
    },
    {
      t: { en: "Privacy vs security", de: "Privatsphäre vs. Sicherheit", es: "Privacidad o seguridad", fr: "Vie privée ou sécurité", it: "Privacy o sicurezza", pt: "Privacidade ou segurança", pl: "Prywatność czy bezpieczeństwo", uk: "Приватність чи безпека" },
      h: {
        en: ["We trade privacy for…", "The danger is that…", "A reasonable balance would be…"],
        de: ["Wir tauschen Privatsphäre gegen…", "Die Gefahr ist, dass…", "Ein vernünftiger Kompromiss wäre…"],
        es: ["Cambiamos privacidad por…", "El peligro es que…", "Un equilibrio razonable sería…"],
        fr: ["Nous échangeons notre vie privée contre…", "Le danger, c'est que…", "Un équilibre raisonnable serait…"],
        it: ["Scambiamo la privacy con…", "Il pericolo è che…", "Un equilibrio ragionevole sarebbe…"],
        pt: ["Nós trocamos privacidade por…", "O perigo é que…", "Um equilíbrio razoável seria…"],
        pl: ["Wymieniamy prywatność na…", "Niebezpieczeństwo polega na tym, że…", "Rozsądną równowagą byłoby…"],
        uk: ["Ми міняємо приватність на…", "Небезпека в тому, що…", "Розумний баланс — це…"],
      },
    },
    {
      t: { en: "Editing human genes", de: "Gene verändern?", es: "Editar genes humanos", fr: "Modifier les gènes humains", it: "Modificare i geni umani", pt: "Editar genes humanos", pl: "Edycja ludzkich genów", uk: "Редагування генів людини" },
      h: {
        en: ["Gene editing could allow us to…", "The ethical problem is…", "We should draw the line at…"],
        de: ["Gentechnik könnte es ermöglichen…", "Das ethische Problem ist…", "Die Grenze sollte bei … liegen"],
        es: ["La edición genética podría permitirnos…", "El problema ético es…", "Deberíamos poner el límite en…"],
        fr: ["La modification génétique pourrait permettre…", "Le problème éthique, c'est…", "Il faudrait fixer la limite à…"],
        it: ["L'editing genetico potrebbe permetterci di…", "Il problema etico è…", "Dovremmo fissare il limite a…"],
        pt: ["A edição genética poderia nos permitir…", "O problema ético é…", "Deveríamos traçar o limite em…"],
        pl: ["Edycja genów mogłaby pozwolić nam…", "Problem etyczny polega na…", "Granicę powinniśmy postawić przy…"],
        uk: ["Редагування генів могло б дозволити нам…", "Етична проблема в тому, що…", "Межу варто провести на…"],
      },
    },
    {
      t: { en: "Is space worth the cost?", de: "Lohnt sich die Raumfahrt?", es: "¿Vale la pena el espacio?", fr: "L'espace vaut-il le coût ?", it: "Lo spazio vale la spesa?", pt: "O espaço vale o custo?", pl: "Czy kosmos jest wart kosztów?", uk: "Чи вартий космос грошей?" },
      h: {
        en: ["Billions are spent on…", "Supporters argue that…", "That money could instead…"],
        de: ["Milliarden werden für … ausgegeben", "Befürworter argumentieren, dass…", "Dieses Geld könnte stattdessen…"],
        es: ["Se gastan miles de millones en…", "Los defensores argumentan que…", "Ese dinero podría en cambio…"],
        fr: ["Des milliards sont dépensés pour…", "Les partisans affirment que…", "Cet argent pourrait plutôt…"],
        it: ["Si spendono miliardi per…", "I sostenitori affermano che…", "Quei soldi potrebbero invece…"],
        pt: ["Bilhões são gastos com…", "Os defensores argumentam que…", "Esse dinheiro poderia, em vez disso…"],
        pl: ["Miliardy wydaje się na…", "Zwolennicy twierdzą, że…", "Te pieniądze mogłyby zamiast tego…"],
        uk: ["Мільярди витрачаються на…", "Прихильники стверджують, що…", "Ці гроші могли б натомість…"],
      },
    },
    {
      t: { en: "Should voting be mandatory?", de: "Wahlpflicht: ja oder nein?", es: "¿Voto obligatorio?", fr: "Le vote obligatoire ?", it: "Voto obbligatorio?", pt: "O voto deveria ser obrigatório?", pl: "Obowiązkowe głosowanie?", uk: "Чи має голосування бути обов'язковим?" },
      h: {
        en: ["In a democracy, voting is…", "Forcing people to vote would…", "A better solution might be…"],
        de: ["In einer Demokratie ist Wählen…", "Wahlpflicht würde…", "Eine bessere Lösung wäre…"],
        es: ["En una democracia, votar es…", "Obligar a votar haría que…", "Una solución mejor sería…"],
        fr: ["En démocratie, voter est…", "Forcer les gens à voter…", "Une meilleure solution serait…"],
        it: ["In democrazia, votare è…", "Obbligare la gente a votare…", "Una soluzione migliore sarebbe…"],
        pt: ["Numa democracia, votar é…", "Obrigar as pessoas a votar…", "Uma solução melhor seria…"],
        pl: ["W demokracji głosowanie jest…", "Zmuszanie ludzi do głosowania…", "Lepszym rozwiązaniem byłoby…"],
        uk: ["У демократії голосування —…", "Примус до голосування призвів би…", "Кращим рішенням було б…"],
      },
    },
    {
      t: { en: "Mental health today", de: "Psychische Gesundheit heute", es: "La salud mental hoy", fr: "La santé mentale aujourd'hui", it: "La salute mentale oggi", pt: "Saúde mental hoje", pl: "Zdrowie psychiczne dziś", uk: "Ментальне здоров'я сьогодні" },
      h: {
        en: ["Modern life creates stress because…", "We talk about it more since…", "What actually helps is…"],
        de: ["Das moderne Leben erzeugt Stress, weil…", "Wir sprechen mehr darüber, seit…", "Was wirklich hilft, ist…"],
        es: ["La vida moderna genera estrés porque…", "Hablamos más de ello desde…", "Lo que realmente ayuda es…"],
        fr: ["La vie moderne crée du stress parce que…", "On en parle plus depuis…", "Ce qui aide vraiment, c'est…"],
        it: ["La vita moderna crea stress perché…", "Ne parliamo di più da quando…", "Ciò che aiuta davvero è…"],
        pt: ["A vida moderna gera estresse porque…", "Falamos mais sobre isso desde…", "O que realmente ajuda é…"],
        pl: ["Współczesne życie tworzy stres, bo…", "Mówimy o tym więcej, odkąd…", "To, co naprawdę pomaga, to…"],
        uk: ["Сучасне життя створює стрес, бо…", "Ми говоримо про це більше, відколи…", "Що справді допомагає, так це…"],
      },
    },
    {
      t: { en: "The four-day work week", de: "Die Vier-Tage-Woche", es: "La semana de cuatro días", fr: "La semaine de quatre jours", it: "La settimana di quattro giorni", pt: "A semana de quatro dias", pl: "Czterodniowy tydzień pracy", uk: "Чотириденний робочий тиждень" },
      h: {
        en: ["Trials have shown that…", "Employers worry that…", "In my field, it would…"],
        de: ["Versuche haben gezeigt, dass…", "Arbeitgeber befürchten, dass…", "In meinem Bereich würde es…"],
        es: ["Las pruebas han demostrado que…", "Los empleadores temen que…", "En mi sector, supondría…"],
        fr: ["Les essais ont montré que…", "Les employeurs craignent que…", "Dans mon domaine, ça…"],
        it: ["Gli esperimenti hanno mostrato che…", "I datori di lavoro temono che…", "Nel mio settore, sarebbe…"],
        pt: ["Os testes mostraram que…", "Os empregadores temem que…", "Na minha área, isso…"],
        pl: ["Testy pokazały, że…", "Pracodawcy obawiają się, że…", "W mojej branży to by…"],
        uk: ["Експерименти показали, що…", "Роботодавці побоюються, що…", "У моїй сфері це б…"],
      },
    },
    {
      t: { en: "Globalization: winners and losers", de: "Globalisierung: Gewinner und Verlierer", es: "Globalización: ganadores y perdedores", fr: "Mondialisation : gagnants et perdants", it: "Globalizzazione: vincitori e vinti", pt: "Globalização: vencedores e perdedores", pl: "Globalizacja: wygrani i przegrani", uk: "Глобалізація: хто виграв, хто програв" },
      h: {
        en: ["Globalization has brought us…", "The losers are often…", "Local cultures respond by…"],
        de: ["Die Globalisierung hat uns … gebracht", "Die Verlierer sind oft…", "Lokale Kulturen reagieren, indem…"],
        es: ["La globalización nos ha traído…", "Los perdedores suelen ser…", "Las culturas locales responden…"],
        fr: ["La mondialisation nous a apporté…", "Les perdants sont souvent…", "Les cultures locales réagissent en…"],
        it: ["La globalizzazione ci ha portato…", "I perdenti sono spesso…", "Le culture locali reagiscono…"],
        pt: ["A globalização nos trouxe…", "Os perdedores costumam ser…", "As culturas locais respondem…"],
        pl: ["Globalizacja przyniosła nam…", "Przegranymi są często…", "Lokalne kultury reagują…"],
        uk: ["Глобалізація принесла нам…", "Ті, хто програв, — це часто…", "Локальні культури відповідають тим, що…"],
      },
    },
    {
      t: { en: "Charity: duty or choice?", de: "Spenden: Pflicht oder Wahl?", es: "Caridad: ¿deber u opción?", fr: "La charité : devoir ou choix ?", it: "Beneficenza: dovere o scelta?", pt: "Caridade: dever ou escolha?", pl: "Dobroczynność: obowiązek czy wybór?", uk: "Благодійність: обов'язок чи вибір?" },
      h: {
        en: ["Those who have more should…", "Charity can also harm when…", "Instead of donations, we could…"],
        de: ["Wer mehr hat, sollte…", "Spenden können auch schaden, wenn…", "Statt Spenden könnten wir…"],
        es: ["Quien tiene más debería…", "La caridad también daña cuando…", "En vez de donaciones, podríamos…"],
        fr: ["Ceux qui ont plus devraient…", "La charité peut aussi nuire quand…", "Au lieu des dons, on pourrait…"],
        it: ["Chi ha di più dovrebbe…", "La beneficenza può anche nuocere quando…", "Invece delle donazioni, potremmo…"],
        pt: ["Quem tem mais deveria…", "A caridade também pode prejudicar quando…", "Em vez de doações, poderíamos…"],
        pl: ["Ci, którzy mają więcej, powinni…", "Dobroczynność może też szkodzić, gdy…", "Zamiast darowizn moglibyśmy…"],
        uk: ["Ті, хто має більше, повинні…", "Благодійність може й шкодити, коли…", "Замість пожертв ми могли б…"],
      },
    },
    {
      t: { en: "Fake news and trust", de: "Fake News und Vertrauen", es: "Noticias falsas y confianza", fr: "Fake news et confiance", it: "Fake news e fiducia", pt: "Fake news e confiança", pl: "Fake newsy i zaufanie", uk: "Фейки і довіра до медіа" },
      h: {
        en: ["Misinformation spreads because…", "To check facts, I…", "Schools should teach…"],
        de: ["Falschinformationen verbreiten sich, weil…", "Um Fakten zu prüfen, …", "Schulen sollten … lehren"],
        es: ["La desinformación se propaga porque…", "Para verificar datos, yo…", "Las escuelas deberían enseñar…"],
        fr: ["La désinformation se répand parce que…", "Pour vérifier les faits, je…", "L'école devrait enseigner…"],
        it: ["La disinformazione si diffonde perché…", "Per verificare i fatti, io…", "Le scuole dovrebbero insegnare…"],
        pt: ["A desinformação se espalha porque…", "Para checar os fatos, eu…", "As escolas deveriam ensinar…"],
        pl: ["Dezinformacja szerzy się, bo…", "Żeby sprawdzić fakty, ja…", "Szkoły powinny uczyć…"],
        uk: ["Дезінформація шириться, бо…", "Щоб перевірити факти, я…", "Школи мали б навчати…"],
      },
    },
    {
      t: { en: "Limits of free speech", de: "Grenzen der Redefreiheit", es: "Límites de la libertad de expresión", fr: "Les limites de la liberté d'expression", it: "I limiti della libertà di parola", pt: "Os limites da liberdade de expressão", pl: "Granice wolności słowa", uk: "Межі свободи слова" },
      h: {
        en: ["Free speech protects…", "It should end where…", "Who decides is the problem, because…"],
        de: ["Redefreiheit schützt…", "Sie sollte dort enden, wo…", "Wer entscheidet, ist das Problem, denn…"],
        es: ["La libertad de expresión protege…", "Debería terminar donde…", "El problema es quién decide, porque…"],
        fr: ["La liberté d'expression protège…", "Elle devrait s'arrêter là où…", "Le problème, c'est qui décide, car…"],
        it: ["La libertà di parola protegge…", "Dovrebbe finire dove…", "Il problema è chi decide, perché…"],
        pt: ["A liberdade de expressão protege…", "Ela deveria terminar onde…", "Quem decide é o problema, porque…"],
        pl: ["Wolność słowa chroni…", "Powinna kończyć się tam, gdzie…", "Problemem jest, kto decyduje, bo…"],
        uk: ["Свобода слова захищає…", "Вона має закінчуватися там, де…", "Проблема в тому, хто вирішує, адже…"],
      },
    },
    {
      t: { en: "Raising kids with screens", de: "Kinder und Bildschirme", es: "Niños y pantallas", fr: "Enfants et écrans", it: "Bambini e schermi", pt: "Criar filhos com telas", pl: "Dzieci i ekrany", uk: "Діти та ґаджети" },
      h: {
        en: ["Children today grow up with…", "Banning screens completely would…", "A healthy balance looks like…"],
        de: ["Kinder wachsen heute mit … auf", "Bildschirme ganz zu verbieten würde…", "Eine gesunde Balance wäre…"],
        es: ["Los niños hoy crecen con…", "Prohibir las pantallas del todo…", "Un equilibrio sano sería…"],
        fr: ["Les enfants grandissent aujourd'hui avec…", "Interdire totalement les écrans…", "Un équilibre sain ressemblerait à…"],
        it: ["I bambini oggi crescono con…", "Vietare del tutto gli schermi…", "Un equilibrio sano sarebbe…"],
        pt: ["As crianças hoje crescem com…", "Proibir telas totalmente…", "Um equilíbrio saudável seria…"],
        pl: ["Dzieci dorastają dziś z…", "Całkowity zakaz ekranów by…", "Zdrowa równowaga to…"],
        uk: ["Діти сьогодні ростуть із…", "Повна заборона ґаджетів призвела б…", "Здоровий баланс — це…"],
      },
    },
    {
      t: { en: "Does prison work?", de: "Funktioniert Gefängnis?", es: "¿Funciona la cárcel?", fr: "La prison fonctionne-t-elle ?", it: "Il carcere funziona?", pt: "A prisão funciona?", pl: "Czy więzienie działa?", uk: "Чи працює в'язниця?" },
      h: {
        en: ["The purpose of punishment is…", "Statistics on reoffending show…", "An alternative would be…"],
        de: ["Der Zweck von Strafe ist…", "Rückfallstatistiken zeigen…", "Eine Alternative wäre…"],
        es: ["El propósito del castigo es…", "Las cifras de reincidencia muestran…", "Una alternativa sería…"],
        fr: ["Le but de la punition est…", "Les chiffres de récidive montrent…", "Une alternative serait…"],
        it: ["Lo scopo della punizione è…", "I dati sulla recidiva mostrano…", "Un'alternativa sarebbe…"],
        pt: ["O objetivo da punição é…", "As estatísticas de reincidência mostram…", "Uma alternativa seria…"],
        pl: ["Celem kary jest…", "Statystyki recydywy pokazują…", "Alternatywą byłoby…"],
        uk: ["Мета покарання —…", "Статистика рецидивів показує…", "Альтернативою було б…"],
      },
    },
    {
      t: { en: "The future of food", de: "Die Zukunft des Essens", es: "El futuro de la comida", fr: "L'avenir de l'alimentation", it: "Il futuro del cibo", pt: "O futuro da comida", pl: "Przyszłość jedzenia", uk: "Майбутнє їжі" },
      h: {
        en: ["Producing meat costs the planet…", "Lab-grown alternatives are…", "In 50 years, we will eat…"],
        de: ["Fleischproduktion kostet den Planeten…", "Laborfleisch ist…", "In 50 Jahren essen wir…"],
        es: ["Producir carne le cuesta al planeta…", "Las alternativas de laboratorio son…", "En 50 años comeremos…"],
        fr: ["Produire de la viande coûte à la planète…", "Les alternatives de laboratoire sont…", "Dans 50 ans, on mangera…"],
        it: ["Produrre carne costa al pianeta…", "Le alternative in laboratorio sono…", "Tra 50 anni mangeremo…"],
        pt: ["Produzir carne custa ao planeta…", "As alternativas de laboratório são…", "Em 50 anos, vamos comer…"],
        pl: ["Produkcja mięsa kosztuje planetę…", "Alternatywy z laboratorium są…", "Za 50 lat będziemy jeść…"],
        uk: ["Виробництво м'яса коштує планеті…", "Альтернативи з лабораторії —…", "Через 50 років ми їстимемо…"],
      },
    },
    {
      t: { en: "Universal basic income", de: "Bedingungsloses Grundeinkommen", es: "Renta básica universal", fr: "Le revenu universel", it: "Il reddito di base", pt: "Renda básica universal", pl: "Bezwarunkowy dochód podstawowy", uk: "Безумовний базовий дохід" },
      h: {
        en: ["The idea is that everyone gets…", "Critics say people would…", "Pilot programs revealed…"],
        de: ["Die Idee ist, dass jeder … bekommt", "Kritiker sagen, die Leute würden…", "Pilotprojekte zeigten…"],
        es: ["La idea es que todos reciban…", "Los críticos dicen que la gente…", "Los programas piloto revelaron…"],
        fr: ["L'idée, c'est que chacun reçoive…", "Les critiques disent que les gens…", "Les programmes pilotes ont révélé…"],
        it: ["L'idea è che tutti ricevano…", "I critici dicono che la gente…", "I programmi pilota hanno rivelato…"],
        pt: ["A ideia é que todos recebam…", "Os críticos dizem que as pessoas…", "Os programas-piloto revelaram…"],
        pl: ["Chodzi o to, że każdy dostaje…", "Krytycy mówią, że ludzie by…", "Programy pilotażowe pokazały…"],
        uk: ["Ідея в тому, що кожен отримує…", "Критики кажуть, що люди б…", "Пілотні програми показали…"],
      },
    },
    {
      t: { en: "Tourism: blessing or burden?", de: "Tourismus: Segen oder Last?", es: "Turismo: ¿bendición o carga?", fr: "Le tourisme : chance ou fardeau ?", it: "Turismo: fortuna o peso?", pt: "Turismo: bênção ou fardo?", pl: "Turystyka: dar czy ciężar?", uk: "Туризм: благо чи тягар?" },
      h: {
        en: ["Tourism brings cities…", "Locals suffer when…", "Cities like Venice have started to…"],
        de: ["Tourismus bringt Städten…", "Einheimische leiden, wenn…", "Städte wie Venedig haben begonnen…"],
        es: ["El turismo aporta a las ciudades…", "Los vecinos sufren cuando…", "Ciudades como Venecia han empezado a…"],
        fr: ["Le tourisme apporte aux villes…", "Les habitants souffrent quand…", "Des villes comme Venise ont commencé à…"],
        it: ["Il turismo porta alle città…", "I residenti soffrono quando…", "Città come Venezia hanno iniziato a…"],
        pt: ["O turismo traz às cidades…", "Os moradores sofrem quando…", "Cidades como Veneza começaram a…"],
        pl: ["Turystyka daje miastom…", "Mieszkańcy cierpią, gdy…", "Miasta jak Wenecja zaczęły…"],
        uk: ["Туризм дає містам…", "Місцеві страждають, коли…", "Міста на кшталт Венеції почали…"],
      },
    },
    {
      t: { en: "A world that grows old", de: "Eine alternde Welt", es: "Un mundo que envejece", fr: "Un monde qui vieillit", it: "Un mondo che invecchia", pt: "Um mundo que envelhece", pl: "Starzejący się świat", uk: "Світ, що старіє" },
      h: {
        en: ["Birth rates are falling because…", "An older society means…", "To adapt, countries could…"],
        de: ["Die Geburtenraten sinken, weil…", "Eine ältere Gesellschaft bedeutet…", "Um sich anzupassen, könnten Länder…"],
        es: ["La natalidad cae porque…", "Una sociedad más vieja significa…", "Para adaptarse, los países podrían…"],
        fr: ["La natalité baisse parce que…", "Une société plus âgée signifie…", "Pour s'adapter, les pays pourraient…"],
        it: ["Le nascite calano perché…", "Una società più anziana significa…", "Per adattarsi, i paesi potrebbero…"],
        pt: ["A taxa de natalidade está caindo porque…", "Uma sociedade mais velha significa…", "Para se adaptar, os países poderiam…"],
        pl: ["Dzietność spada, bo…", "Starsze społeczeństwo oznacza…", "Aby się dostosować, kraje mogłyby…"],
        uk: ["Народжуваність падає, бо…", "Старше суспільство означає…", "Щоб адаптуватися, країни могли б…"],
      },
    },
    {
      t: { en: "Are video games art?", de: "Sind Videospiele Kunst?", es: "¿Son arte los videojuegos?", fr: "Les jeux vidéo sont-ils de l'art ?", it: "I videogiochi sono arte?", pt: "Videogames são arte?", pl: "Czy gry wideo to sztuka?", uk: "Чи є відеоігри мистецтвом?" },
      h: {
        en: ["Games combine music, story and…", "Unlike films, games let you…", "A game that felt like art to me…"],
        de: ["Spiele vereinen Musik, Geschichte und…", "Anders als Filme lassen Spiele dich…", "Ein Spiel, das für mich Kunst war…"],
        es: ["Los juegos combinan música, historia y…", "A diferencia del cine, los juegos te dejan…", "Un juego que me pareció arte…"],
        fr: ["Les jeux combinent musique, histoire et…", "Contrairement aux films, les jeux te laissent…", "Un jeu qui m'a semblé de l'art…"],
        it: ["I giochi uniscono musica, storia e…", "A differenza dei film, i giochi ti lasciano…", "Un gioco che per me era arte…"],
        pt: ["Os jogos combinam música, história e…", "Diferente dos filmes, os jogos deixam você…", "Um jogo que, para mim, foi arte…"],
        pl: ["Gry łączą muzykę, fabułę i…", "W przeciwieństwie do filmów gry pozwalają ci…", "Gra, która była dla mnie sztuką…"],
        uk: ["Ігри поєднують музику, історію та…", "На відміну від фільмів, ігри дозволяють тобі…", "Гра, яка була для мене мистецтвом…"],
      },
    },
  ],
};

// Filler words (checked as tokens/bigrams, lowercased)
const FILLERS = {
  en: ["um", "uh", "erm", "uhm", "you know", "i mean", "sort of", "kind of", "basically"],
  de: ["äh", "ähm", "halt", "quasi", "sozusagen", "naja", "irgendwie"],
  es: ["eh", "este", "pues", "o sea", "bueno", "como que", "en plan"],
  fr: ["euh", "ben", "bah", "genre", "en fait", "du coup", "quoi", "voilà"],
  it: ["ehm", "cioè", "tipo", "insomma", "diciamo", "praticamente", "allora"],
  pt: ["tipo", "né", "sabe", "meio que", "e tal", "tipo assim"],
  pl: ["yyy", "eee", "no", "jakby", "w sumie", "wiesz", "znaczy", "generalnie"],
  uk: ["е", "ем", "ну", "типу", "коротше", "це саме", "як би", "так би мовити"],
};

// Connectors / linking phrases (signal of coherent speech)
const CONNECTORS = {
  en: ["because", "however", "although", "therefore", "moreover", "for example", "in my opinion", "on the other hand", "first of all", "finally", "in addition", "as a result"],
  de: ["weil", "obwohl", "deshalb", "außerdem", "zum beispiel", "meiner meinung nach", "einerseits", "andererseits", "trotzdem", "zuerst", "schließlich"],
  es: ["porque", "aunque", "por eso", "además", "por ejemplo", "en mi opinión", "sin embargo", "primero", "finalmente", "por lo tanto"],
  fr: ["parce que", "bien que", "donc", "de plus", "par exemple", "à mon avis", "cependant", "d'abord", "enfin", "par conséquent"],
  it: ["perché", "anche se", "quindi", "inoltre", "per esempio", "secondo me", "tuttavia", "prima di tutto", "infine", "di conseguenza"],
  pt: ["porque", "embora", "por isso", "além disso", "por exemplo", "na minha opinião", "no entanto", "por outro lado", "primeiro", "finalmente", "como resultado"],
  pl: ["ponieważ", "chociaż", "dlatego", "poza tym", "na przykład", "moim zdaniem", "jednak", "najpierw", "w końcu", "w rezultacie"],
  uk: ["тому що", "хоча", "тому", "крім того", "наприклад", "на мою думку", "однак", "спочатку", "нарешті", "внаслідок цього"],
};

// Achievements: mark = a typographic monogram inside a thin ring (no pictograms)
const BADGES = [
  { id: "first",    mark: "1",   name: "First minute",       desc: "Finish your first minute" },
  { id: "five",     mark: "5",   name: "Five minutes",       desc: "5 talks completed" },
  { id: "twenty",   mark: "20",  name: "Twenty",             desc: "20 talks completed" },
  { id: "streak3",  mark: "3",   name: "Three-day streak",   desc: "Practice 3 days in a row" },
  { id: "streak7",  mark: "7",   name: "A week of practice", desc: "Practice 7 days in a row" },
  { id: "words100", mark: "100", name: "Wordsmith",          desc: "100+ words in one minute" },
  { id: "clevel",   mark: "C",   name: "Level C",            desc: "Reach a C1 or C2 score" },
  { id: "polyglot", mark: "III", name: "Polyglot",           desc: "Practice in three languages" },
];
